Next_Conditions = {
    # Table 1. Systemic arteries

    # # cardiovascular system = {
    # "VT_pa": [6.84],
    # "VT_pp": [116.6775],
    # "VT_pv": [114],
    # "Q_pa": [0],
    # "VT_la": [40],
    # "VT_lv": [160],
    # "VT_ra": [44],
    # "VT_rv": [160],
    # "VT_sv": [1361.6],
    # "VT_bv": [279.49],
    # "VT_hv": [93.16],
    # "VT_rmv": [190.95],
    # "VT_amv": [286.4],
    # "VT_ev": [607.8],
    # "P_sp": [66],
    # "V_sa": [22],
    # "P_sa": [70],
    # "Q_sa": [0],
    # "VT_vc": [350],

# cardiovascular system = {
    "VT_pa": [70],
    "VT_pp": [200],
    "VT_pv": [215],
    "Q_pa": [0], # not sure
    "VT_la": [20],
    "VT_lv": [150],
    "VT_ra": [20],
    "VT_rv": [180],
    "VT_sv": [1400],
    "VT_bv": [300],
    "VT_hv": [100],
    "VT_rmv": [200],
    "VT_amv": [300],
    "VT_ev": [400],
    "P_sp": [66], # not sure
    "V_sa": [], #
    "P_sa": [92], # not sure
    "Q_sa": [0], # at ED, Q_sa = 0 so that dP_sa_dt = 0
    "VT_vc": [350],
    "Qi_lv": [],
    "Qi_rv": [],
    "prev_flat_bit": [0],
    "Q_vc": [],
    "alp": [],
    "P_im": [],
    "Q_amv": [],
    "Q_sp": [],
    "Q_ep": [],

    "P_pa": [],
    "P_pp": [],
    "P_pv": [],
    "P_ra": [],
    "P_la": [],
    "P_lv": [],
    "P_rv": [],
    "Pmax_lv": [],
    "V_rv": [],
    "V_ra": [],
    "V_lv": [],
    "V_la": [],
    "Q_lv": [],
    "Q_ra": [],
    "Q_rv": [],
    "P_thor": [],
    "V_vc": [],
    "P_vc": [],
    "V_pa": [],
    "phi": [],
    "phi_atr": [],
    "S": [],
    "V_pv": [],
    "V_pp": [],
    "P_abd": [],


    # state # edited so that total is initially the unstressed volumes

    # "VT_pa": [0],
    # "VT_pp": [116.6775],
    # "VT_pv": [114],
    # "Q_pa": [0], # not sure
    # "VT_la": [24],
    # "VT_lv": [15.908],
    # "VT_ra": [24],
    # "VT_rv": [38.703],
    # "VT_sv": [1361.6],
    # "VT_bv": [279.49],
    # "VT_hv": [93.16],
    # "VT_rmv": [190.95],
    # "VT_amv": [286.4],
    # "VT_ev": [607.8],
    # "P_sp": [0], # not sure
    # "V_sa": [0], # 0 since assume initially volume is unstressed
    # "P_sa": [0], # not sure
    # "Q_sa": [0], # not sure
    # "VT_vc": [123],


    # initial condition of inputs from other controllers
    "Cvb_O2": [],
    "P_bv": [],
    "U": [0],
    "U1": [0],
    "U2": [0],
    "time_since_beat": [0],
    "beta": [0],
    "BF": [0.25], # changed to 0.25 from 1/3 today, forgot why i had it as 1/3, nd is 4 s for t1+t2
    "Vu_ev": [607.8],
    "Vu_amv": [286.4],
    "Vu_rmv": [190.95],
    "Vu_sv": [1361.6],
    "R_ep": [1.655],
    "R_amp": [3.51],
    "R_rmp": [5.27],
    "R_sp": [2.49],
    "R_bp": [6.57],
    "R_hp": [19.71],
    "HR": [1.2], # changed to 1.2 from 1.72, T0 was set at 0.58. doesnt make sense for t0 to be that high
    "Emax_lv": [2.392],
    "Emax_rv": [1.412],
    "I": [0],
    "P_ev": [],
    "V_u": [],
    "V_sv": [],
    "V_rmv": [],
    "V_amv": [],
    "V_bv": [],
    "V_hv": [],
    "HR1": [],
    "check": [0],
    "theta_ao": [],
    "AR_ao": [],
    "d2theta_ao_dt2": [],
    "dVT_la_dt": [700],
    "dPmax_la_dt": [],
    "dVT_ra_dt": [100],
    "dPmax_ra_dt": [],
    "phi_cond": [],

    # cardiovascular controller
    "theta_change_O2_sp": [0],
    "theta_change_CO2_sp": [0],
    "theta_change_O2_sv": [0],
    "theta_change_CO2_sv": [0],
    "theta_change_O2_sh": [0],
    "theta_change_CO2_sh": [0],
    "P_tilda": [80],
    "f_ac": [8.0807],
    "f_ap": [4.4492],
    "R_ep_change": [0],
    "R_sp_change": [0],
    "R_rmp_n_change": [0],
    "R_amp_n_change": [0],
    "Vu_ev_change": [0],
    "Vu_sv_change": [0],
    "Vu_rmv_change": [0],
    "Vu_amv_change": [0],
    "Emax_lv_change": [0],
    "Emax_rv_change": [0],
    "Ts_change": [0],
    "Tv_change": [0],
    "Q_bv": [],
    "R_bv": [],
    "xb_O2": [0],
    "xb_CO2": [0],
    "xh_O2": [0],
    "xh_CO2": [0],
    "Wh": [12660],
    "xrm_O2": [0],
    "xrm_CO2": [0],
    "xam_O2": [0],
    "xM": [0],
    "x_met": [0],
    "Nt": [],
    "P_amv": [],
    "Q_jp": [],
    "Vu_ev1": [],
    "Vu_sv1": [],
    "Vu_rmv1": [],
    "Vu_amv1": [],
    "Emax_lv1": [],
    "Emax_rv1": [],
    "source_values": [0],

    # initial condition of inputs from other controllers
    "Wh_lv": [10800],
    "Wh_rv": [1860],
    "Ca_O2": [0.2],
    "Ca_CO2": [0.2],
    # "Q_bp": 0,
    "Q_hp": [10],
    "Q_rmp": [10],
    "Q_amp": [10],
    # "times": [0],
    # "f_sp_history": [],
    # "f_sh_history": [],
    # "f_v_history": [],
    # "phi_met_history": [],
    "VT": [0.73], # changed from 0.4 to the original parameter
    "dP_sa_dt": [0],
    # "PaO2": 80,
    # "PaCO2": 40,
    # "MRTCO2":
    "TI": [1.8],
    "VE_flow": [],
    # "previous_VE": [],

    # Respiratory mechanics
    "V": [0],
    "alpha": [0],
    "Vflow_ua": [0],
    "Vflow_LA": [0],

    # other inputs
    # "Nd": [0, 0, 0, 0, 0, 0],

    # Respiratory controller
    "VE_integral": [0],

    # other inputs
    "dV_dt": [0],
    # "previous_dV_dt": [0],
    "P_musc": [0],
    "WI": [0],
    "WE": [0],
    # "previous_WI": [0],
    # "previous_WE": [0],
    # "Pa_CO2": 40,
    # "Pa_O2": 80,
    "PbCO2": [48.5383],
    # "MRV": 0,

    # Gas exchange
    "Pd_1_O2": [104.3637],
    "Pd_1_CO2": [39.5616],
    "Pd_2_O2": [104.3637],
    "Pd_2_CO2": [39.6736],
    "Pd_3_O2": [104.0505],
    "Pd_3_CO2": [39.8127],
    "Pd_4_O2": [103.8005],
    "Pd_4_CO2": [40.0061],
    "Pd_5_O2": [103.3579],
    "Pd_5_CO2": [40.3359],
    "Pa_O2": [100], # ignore: set 0 here, but it is another value initially from Gas_Exchange.py
    "Pa_CO2": [40], # ignore: set 0 here, but it is another value initially from Gas_Exchange.py
    "dPa_O2_dt": [0.3557],
    "dPa_CO2_dt": [-0.2465],
    "PA_O2": [102.5153],
    "PA_CO2": [40.9432],
    "PvbCO2": [43.7], # set 0 here, but it is another value initially from Gas_Exchange.py
    "PCSFCO2": [43.6],
    "MRTO2": [0.33/60],
    "MRTCO2": [0.3/60],
    "Cv_O2": [0.1639],
    "Cv_CO2": [0.5247],
    "MRV": [0],
    "FO2": [],
    "FCO2":[],
    "QT": [],
    "phi_atr1": [],
    "phi_atr2": [],
    # other inputs from other systems
    # "dV_dt":
    # "V": [0],
    "Q_pp": [10],
    "Q_bp": [10], # or 10.5
    "Q_la": [10], # set based on simulation results and visually looking at plot (need to change)
    "VD": [0.15],
    "Pmax_rv": [],
    "Pmax_ra": [],
    "Pmax_la": [],

    # exp inputs/time history
    "f_sp_history": [],
    "f_sh_history": [],
    "f_v_history": [],
    "f_sv_history": [],
    "phi_met_history": [0],
    "phi_met": [0],
    "previous_VE": [0],
    "Nd": [0, 20, -5, 0.4, 1.8, 2.2], # a0, a1, a2, tau, t1, t2
    "previous_WI": [0],
    "previous_WE": [0],
    "previous_dV_dt": [0],
    "Pa_O2_history": [100],
    "Pa_CO2_history": [40],
    "Pb_CO2_history": [48.5383],
    "Pb_CO2": [48.5383],
    "G_AW": [1],
    "G_AW_guess": [1],
    "P_ua": [-1],
    "t_eval1": [],
    "t_eval2": [],
    "t_eval3": [],
    "t_eval4": [],
    "t_eval5": [],
    "t_eval6": [],
    "P_pl": [],
    "VAflow": [],
    "T": [],

    "PamO2": [],
    "PamCO2": [],
    "PmbCO2": [],
    "time_history": [],
    "all_time": [],
}